services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: test $$(mongosh --quiet --eval "rs.status().ok") -eq 1
      interval: 5s
      timeout: 5s
      retries: 10
  mongo-init-replica:
    image: mongo:6
    restart: "no"
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
        mongosh --host mongo:27017 --eval \"
          rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: 'mongo:27017' }]
          })
        \"
      "

volumes:
  mongo_data:
