openapi: 3.0.3
info:
  title: Cooking API
  version: 1.0.0

components:
  schemas:
    IngredientPublic:
      type: object
      example:
        _id: 650a624c88593a100f7234c2
        category: Warzywa
        title: Pomidor
        unit: kg
        owner: null
    IngredientUser:
      type: object
      example:
        _id: 650a624c88593a100f7234c2
        category: Warzywa
        title: Pomidor
        unit: kg
        owner: 652f59f40f1b2a001f2c4a12
        deletable: true
